import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import SideMenu from '@/components/sidebar/SideMenu';
import cloudinary from 'cloudinary';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        {/* NAVBAR */}
        <div className='hidden flex-col md:flex'>
          <div className='border-b'>
            <div className='flex h-16 items-center px-4 container mx-auto '>
              GALLERIO
              <div className='ml-auto flex items-center space-x-4'>
                <Avatar>
                  <AvatarImage src='https://github.com/shadcn.png' />
                  <AvatarFallback>CN</AvatarFallback>
                </Avatar>
              </div>
            </div>
          </div>
        </div>
        <div className='flex '>
          <SideMenu />
          <div className='w-full px-4 pt-12'>{children}</div>
        </div>
      </body>
    </html>
  );
}
